from enum import Enum
from typing import Optional, Tuple

from torch import TensorBase

# Defined in torch/csrc/functorch/init.cpp

def _set_dynamic_layer_keys_included(included: bool) -> None: ...
def get_unwrapped(tensor: TensorBase) -> TensorBase: ...
def is_batchedtensor(tensor: TensorBase) -> bool: ...
def is_functionaltensor(tensor: TensorBase) -> bool: ...
def is_functorch_wrapped_tensor(tensor: TensorBase) -> bool: ...
def is_gradtrackingtensor(tensor: TensorBase) -> bool: ...
def maybe_get_bdim(tensor: TensorBase) -> int: ...
def maybe_get_level(tensor: TensorBase) -> int: ...
def maybe_current_level() -> Optional[int]: ...
def unwrap_if_dead(tensor: TensorBase) -> TensorBase: ...
def _unwrap_for_grad(tensor: TensorBase, level: int) -> TensorBase: ...
def _wrap_for_grad(tensor: TensorBase, level: int) -> TensorBase: ...
def _unwrap_batched(
    tensor: TensorBase, level: int
) -> Tuple[TensorBase, Optional[int]]: ...
def current_level() -> int: ...
def _add_batch_dim(tensor: TensorBase, bdim: int, level: int) -> TensorBase: ...
def set_single_level_autograd_function_allowed(allowed: bool) -> None: ...
def get_single_level_autograd_function_allowed() -> bool: ...
def _unwrap_functional_tensor(
    tensor: TensorBase, reapply_views: bool
) -> TensorBase: ...
def _wrap_functional_tensor(tensor: TensorBase, level: int) -> TensorBase: ...
def _vmap_increment_nesting(batch_size: int, randomness: str) -> int: ...
def _vmap_decrement_nesting() -> int: ...
def _grad_increment_nesting() -> int: ...
def _grad_decrement_nesting() -> int: ...

# Defined in aten/src/ATen/functorch/Interpreter.h
class TransformType(Enum):
    Torch: TransformType = ...
    Vmap: TransformType = ...
    Grad: TransformType = ...
    Jvp: TransformType = ...
    Functionalize: TransformType = ...

class RandomnessType(Enum):
    Error: TransformType = ...
    Same: TransformType = ...
    Different: TransformType = ...

class CInterpreter:
    def key(self) -> TransformType: ...
    def level(self) -> int: ...

class CGradInterpreterPtr:
    def __init__(self, interpreter: CInterpreter): ...
    def lift(self, Tensor) -> TensorBase: ...
    def prevGradMode(self) -> bool: ...

class CJvpInterpreterPtr:
    def __init__(self, interpreter: CInterpreter): ...
    def lift(self, Tensor) -> TensorBase: ...
    def prevFwdGradMode(self) -> bool: ...

class CFunctionalizeInterpreterPtr:
    def __init__(self, interpreter: CInterpreter): ...
    def key(self) -> TransformType: ...
    def level(self) -> int: ...
    def functionalizeAddBackViews(self) -> bool: ...

class CVmapInterpreterPtr:
    def __init__(self, interpreter: CInterpreter): ...
    def key(self) -> TransformType: ...
    def level(self) -> int: ...
    def batchSize(self) -> int: ...
    def randomness(self) -> RandomnessType: ...

class DynamicLayer: ...

def get_interpreter_stack() -> list[CInterpreter]: ...
def peek_interpreter_stack() -> CInterpreter: ...
def pop_dynamic_layer_stack() -> DynamicLayer: ...
def push_dynamic_layer_stack(dl: DynamicLayer) -> int: ...
