from typing import AnyStr, List

from torch import TensorBase

class UndefinedGrad:
    def __init__(self) -> None: ...
    def __call__(self, *inputs: TensorBase) -> List[TensorBase]: ...

class DelayedError:
    def __init__(self, msg: AnyStr, num_inputs: int) -> None: ...
    def __call__(self, inputs: List[TensorBase]) -> List[TensorBase]: ...
